version: 2

models:
  - name: fact_trips
    description: "The final curated fact table. Reconciled to 1,000 trips and $51,122.35 revenue."
    columns:
      - name: trip_id
        tests:
          - unique
          - not_null

      - name: customer_sk
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_sk

      - name: driver_sk
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_driver')
                field: driver_sk

      - name: pickup_location_sk
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_locations')
                field: location_sk

  - name: dim_customers
    columns:
      - name: customer_sk
        tests:
          - unique
          - not_null

  - name: dim_driver
    columns:
      - name: driver_sk
        tests:
          - unique
          - not_null

  - name: dim_locations
    columns:
      - name: location_sk
        tests:
          - unique
          - not_null

  - name: dim_payments
    columns:
      - name: payment_sk
        tests:
          - unique
          - not_null

  - name: dim_vehicles
    columns:
      - name: vehicle_sk
        tests:
          - unique
          - not_null
